export interface ExiflyOpts {
  debug: boolean;
}

// 0th IFD
export enum ZEROTH_IFD {
  'Compression' = 'Compression',
  'ImageDescription' = 'ImageDescription',
  'Make' = 'Make',
  'Model' = 'Model',
  'XResolution' = 'XResolution',
  'YResolution' = 'YResolution',
  'ResolutionUnit' = 'ResolutionUnit',
  'TransferFunction' = 'TransferFunction',
  'Artist' = 'Artist',
  'WhitePoint' = 'WhitePoint',
  'PrimaryChromaticities' = 'PrimaryChromaticities',
  'YcbCrCoefficients' = 'YcbCrCoefficients',
  'ReferenceBlackWhite' = 'ReferenceBlackWhite',
  'Copyright' = 'Copyright',
  'ImageWidth' = 'ImageWidth',
  'ImageLength' = 'ImageLength',
  'BitsPerSample' = 'BitsPerSample',
  'PhotometricInterpretation' = 'PhotometricInterpretation',
  'Orientation' = 'Orientation',
  'SamplesPerPixel' = 'SamplesPerPixel',
  'PlanarConfiguration' = 'PlanarConfiguration',
  'YCbCrSubSampling' = 'YCbCrSubSampling',
  'YCbCrPositioning' = 'YCbCrPositioning',
  'StripOffsets' = 'StripOffsets',
  'RowsPerStrip' = 'RowsPerStrip',
  'StripByteCounts' = 'StripByteCounts',
  'JPEGInterchangeFormat' = 'JPEGInterchangeFormat',
  'JPEGInterchangeFormatLength' = 'JPEGInterchangeFormatLength',
  'Software' = 'Software',
  'DateTime' = 'DateTime',
  'ExifIFDPointer' = 'Exif IFD Pointer',
  'GPSInfoIFDPointer' = 'GPS Info IFD Pointer',
  'InteroperabilityIFDPointer' = 'Interoperability IFD Pointer',
}

// Exif IFD
export enum EXIF_IFD {
  'ExposureTime' = 'ExposureTime',
  'FNumber' = 'FNumber',
  'ExposureProgram' = 'ExposureProgram',
  'SpectralSensitivity' = 'SpectralSensitivity',
  'PhotographicSensitivity' = 'PhotographicSensitivity',
  'OECF' = 'OECF',
  'SensitivityType' = 'SensitivityType',
  'StandardOutputSensitivity' = 'StandardOutputSensitivity',
  'RecommendedExposurelndex' = 'RecommendedExposurelndex',
  'ISOSpeed' = 'ISOSpeed',
  'ISOSpeedLatitudeyyy' = 'ISOSpeedLatitudeyyy',
  'ISOSpeedLatitudezzz' = 'ISOSpeedLatitudezzz',
  'ExifVersion' = 'ExifVersion',
  'DateTimeOriginal' = 'DateTimeOriginal',
  'DateTimeDigitized' = 'DateTimeDigitized',
  'ComponentsConfiguration' = 'ComponentsConfiguration',
  'ShutterSpeedValue' = 'ShutterSpeedValue',
  'ApertureValue' = 'ApertureValue',
  'BrightnessValue' = 'Brightness Value',
  'ExposureBiasValue' = 'ExposureBiasValue',
  'MaxApertureValue' = 'MaxAperture Value',
  'SubjectDistance' = 'SubjectDistance',
  'MeteringMode' = 'MeteringMode',
  'LightSource' = 'LightSource',
  'Flash' = 'Flash',
  'FocalLength' = 'FocalLength',
  'MakerNote' = 'MakerNote',
  'UserComment' = 'UserComment',
  'SubSecTime' = 'SubSecTime',
  'SubSecTimeOriginal' = 'SubSecTimeOriginal',
  'SubSecTimeDigitized' = 'SubSecTimeDigitized',
  'FlashpixVersion' = 'FlashpixVersion',
  'ColorSpace' = 'ColorSpace',
  'RelatedSoundFile' = 'RelatedSoundFile',
  'FlashEnergy' = 'FlashEnergy',
  'SpatialFrequencyResponse' = 'SpatialFrequencyResponse',
  'FocalPlaneX-Resolution' = 'FocalPlaneX-Resolution',
  'FocalPlaneY-Resolution' = 'FocalPlaneY-Resolution',
  'FocalPlane-ResolutionUnit' = 'FocalPlane-ResolutionUnit',
  'Exposurelndex' = 'Exposurelndex',
  'SensingMethod' = 'SensingMethod',
  'FileSource' = 'FileSource',
  'SceneType' = 'SceneType',
  'CFApattern' = 'CFApattern',
  'ExposureMode' = 'ExposureMode',
  'WhiteBalance' = 'WhiteBalance',
  'DigitalZoomRatio' = 'DigitalZoomRatio',
  'FocalLengthIn35mmFilm' = 'FocalLengthIn35mmFilm',
  'SceneCapture Type' = 'SceneCapture Type',
  'GainControl' = 'GainControl',
  'Contrast' = 'Contrast',
  'Saturation' = 'Saturation',
  'Sharpness' = 'Sharpness',
  'DeviceSettingDescription' = 'DeviceSettingDescription',
  'SubjectDistanceRange' = 'SubjectDistanceRange',
  'ImageUniquelD' = 'ImageUniquelD',
  'CameraOwnerName' = 'CameraOwnerName',
  'BodySerialNumber' = 'BodySerialNumber',
  'LensSpecification' = 'LensSpecification',
  'LensMake' = 'LensMake',
  'LensModel' = 'LensModel',
  'LensSerialNumber' = 'LensSerialNumber',
  'Gamma' = 'Gamma',
  'CompressedBitsPerPixel' = 'CompressedBitsPerPixel',
  'PixelXDimension' = 'PixelXDimension',
  'PixelYDimension' = 'PixelYDimension',
  'SubjectArea' = 'SubjectArea',
  'FocalPlaneXResolution' = 'FocalPlaneXResolution',
  'FocalPlaneYResolution' = 'FocalPlaneYResolution',
  'FocalPlaneResolutionUnit' = 'FocalPlaneResolutionUnit',
  'SubjectLocation' = 'SubjectLocation',
  'ExposureIndex' = 'ExposureIndex',
  'CFAPattern' = 'CFAPattern',
  'CustomRendered' = 'CustomRendered',
  'DigitalZoomRation' = 'DigitalZoomRation',
  'SceneCaptureType' = 'SceneCaptureType',
  'ImageUniqueID' = 'ImageUniqueID',
}

// Interoperability IFD
export enum INTEROPERABILITY_IFD {
  'InteroperabilityIndex' = 'InteroperabilityIndex',
}

// GPS info IFD
export enum GPS_INFO_IFD {
  'GPSVersionID' = 'GPSVersionID',
  'GPSLatitudeRef' = 'GPSLatitudeRef',
  'GPSLatitude' = 'GPSLatitude',
  'GPSImgDirection' = 'GPSImgDirection',
  'GPSLongitudeRef' = 'GPSLongitudeRef',
  'GPSLongitude' = 'GPSLongitude',
  'GPSAltitudeRef' = 'GPSAltitudeRef',
  'GPSAltitude' = 'GPSAltitude',
  'GPSTimeStamp' = 'GPSTimeStamp',
  'GPSSatellites' = 'GPSSatellites',
  'GPSStatus' = 'GPSStatus',
  'GPSMeasureMode' = 'GPSMeasureMode',
  'GPSDOP' = 'GPSOP',
  'GPSSpeedRef' = 'GPSSpeedRef',
  'GPSSpeed' = 'GPSSpeed',
  'GPSTrackRef' = 'GPSTrackRef',
  'GPSTrack' = 'GPSTrack',
  'GPSImgDirectionRef' = 'GPSImgDirectionRef',
  'GPSImgDirectionGPSMapDatum' = 'GP SImgDirection GPSMapDatum',
  'GPSDestLatitudeRef' = 'GPSDestLatitudeRef',
  'GPSDestLatitude' = 'GPSDestLatitude',
  'GPSDestLongitudeRef' = 'GPSDestLongitudeRef',
  'GPSDestLongitude' = 'GPSDestLongitude',
  'GPSDestBearingRef' = 'GPSDestBearingRef',
  'GPSDestBearing' = 'GPSDestBearing',
  'GPSDestDistanceRef' = 'GPSDestDistanceRef',
  'GPSDestDistance' = 'GPSDestDistance',
  'GPSProcessingMethod' = 'GPSProcessingMethod',
  'GPSArealnformation' = 'GPSArealnformation',
  'GPSDateStamp' = 'GPSDateStamp',
  'GPSDifferential' = 'GPSDifferential',
  'GPSHPositioningError' = 'GPSHPositioningError',
  'GPSMapDatum' = 'GPSMapDatum',
  'GPSAreaInformation' = 'GPSAreaInformation',
}

// 1st IFD
export enum FIRST_IFD {
  'Compression' = 'Compression',
  'ImageDescription' = 'ImageDescription',
  'Make' = 'Make',
  'Model' = 'Model',
  'TransferFunction' = 'TransferFunction',
  'Artist' = 'Artist',
  'WhitePoint' = 'WhitePoint',
  'PrimaryChromaticities' = 'PrimaryChromaticities',
  'YCbCrCoefficients' = 'YCbCrCoefficients',
  'ReferenceBlackWhite' = 'ReferenceBlackWhite',
  'Copyright' = 'Copyright',
  'ExifIFDPointer' = 'Exif IFD Pointer',
  'GPSInfoIFDPointer' = 'GPS Info IFD Pointer',
}

/**
 * based on CIPA DC-008-2012 Exif Version 2.3
 * @see https://www.cipa.jp/std/documents/e/DC-008-2012_E.pdf
 */
export const EXIF_TAGS = {
  ZEROTH_IFD: ZEROTH_IFD,
  EXIF_IFD: EXIF_IFD,
  GPS_INFO_IFD: GPS_INFO_IFD,
  INTEROPERABILITY_IFD: INTEROPERABILITY_IFD,
  FIRST_IFD: FIRST_IFD,
};
